### ISSUE TITLE
Weather API

### ISSUE THREAD

**Issue by SCScbc-Projects2022** [SCScbc-Projects2022/WeathCon-project-one#3]
## Weather API

- When user submits current city name and destination city, fetch weather api for destination
- when I fetch url, I receive data for city input on first page(destination)
- use json to convert data into response
- populate variables with responses needed for destination current weather, current weather icon, current city's country, and 5-day forecast, 7-day forecast, and 14-day forecast
- function to display weather on page

**Comment by TOVTC** [comment]
mvp/weather-api
