### ISSUE TITLE
First Page and HTML Page Links

### ISSUE THREAD

**Issue by BrennanJLM** [SCScbc-Projects2022/WeathCon-project-one#6]
Create header
Create a header that includes a logo image, and text, to show what the page allows the user to accomplish

Add background
Add image to background

Add text to bottom left of background
“Made By Team WeathCon, 2022”

Add “Where are you from?” input
Add a form dynamically, where the user inputs their current city.  

Add “Where are you going?” input
Add a form dynamically, where the user inputs their destination city.

Add submit button
Add a submit button that links to java.js that accesses the two inputs, and populates the information to corresponding containers on page 2

**Comment by TOVTC** [comment]
feature/dynamic-header

**Comment by TOVTC** [comment]
Design has been changed to two-page static HTML

* Add API to generate dropdown list of possible country and city combinations
* on click, capture dropdown fields and pass as query strings to be used as variables and parameters on page two

**Comment by TOVTC** [comment]
mvp/user-input-handling
user-input-handling
